### ISSUE TITLE
Vim & Rust

### ISSUE THREAD

**Issue by moonglum** [moonglum/dotfiles#60]
Improve the Rust Setup for vim: 

- [ ] [vim-racer](https://github.com/racer-rust/vim-racer)

## Ansible

```yaml
    - name: Download Rust source
      get_url: url=https://static.rust-lang.org/dist/rustc-{{ rust_version }}-src.tar.gz dest=/tmp/rust.tar.gz
    - name: Unarchive Rust source
      unarchive: src=/tmp/rust.tar.gz dest=/tmp copy=false
    - name: Move Rust source
      command: cp /tmp/hub-linux-amd64-2.2.2/bin/hub /usr/local/bin/hub
```
